### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by myt0722** [deep-fingerprinting/df#5]
There were decoding errors as NoDef and WTF experiments, but reading the WalkieTalkie did not report any errors, my experimental environment is python 3.
Show one of the errors:
```
(tensorflow-gpu) F:\df\src>python ClosedWorld_DF_NoDef.py
Using TensorFlow backend.
Training and evaluating DF model for closed-world scenario on non-defended dataset
Number of Epoch:  30
Loading and preparing data for training, and evaluating the model
Loading non-defended dataset for closed-world scenario
Traceback (most recent call last):
  File "ClosedWorld_DF_NoDef.py", line 46, in <module>
    X_train, y_train, X_valid, y_valid, X_test, y_test = LoadDataNoDefCW()
  File "F:\df\src\utility.py", line 17, in LoadDataNoDefCW
    X_train = np.array(pickle.load(handle))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 6: ordinal not in range(128)
```

**Comment by myt0722** [comment]
I have solved this problem: 
`X_train = np.array(pickle.load(handle , encoding='bytes'))`
Dear Authors, can you share your Python code for converting *.csv into ROC curves?
